# Generated by Django 5.2.8 on 2025-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_equipo',
            field=models.BooleanField(default=False),
        ),
    ]
