# Generated by Django 5.2.8 on 2026-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_tiene_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
