# Generated by Django 5.2.8 on 2026-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
