# Generated by Django 5.2.6 on 2026-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljugador',
            name='posicion',
            field=models.CharField(blank=True, choices=[('portero', 'Portero'), ('lateral_derecho', 'Lateral Derecho'), ('defensa_central', 'Defensa Central'), ('lateral_izquierdo', 'Lateral Izquierdo'), ('mediocentro_defensivo', 'Mediocentro Defensivo'), ('mediocentro', 'Mediocentro'), ('mediocentro_ofensivo', 'Mediocentro Ofensivo'), ('interior_izquierda', 'Interior Izquierda'), ('interior_derecha', 'Interior Derecha'), ('extremo_derecho', 'Extremo Derecho'), ('extremo_izquierdo', 'Extremo Izquierdo'), ('segundo_delantero', 'Segundo Delantero'), ('delantero_centro', 'Delantero Centro')], help_text='Posición en el equipo actual (asignada por el entrenador)', max_length=25, null=True),
        ),
    ]
