# Generated by Django 5.2.8 on 2026-01-15 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del equipo')),
                ('color_principal', models.CharField(default='#27a770', max_length=7, validators=[django.core.validators.RegexValidator(message='Introduce un código de color Hexadecimal válido (ej: #27a770)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color Principal')),
                ('color_secundario', models.CharField(default='#504847', max_length=7, validators=[django.core.validators.RegexValidator(message='Introduce un código de color Hexadecimal válido (ej: #27a770)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color Secundario')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección completa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto')),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos_equipos/', verbose_name='Escudo')),
                ('anio_fundacion', models.PositiveIntegerField(help_text='Año en el que se fundó el club', validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2026)], verbose_name='Año de fundación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
