# Generated by Django 5.2.8 on 2026-01-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
