# Generated by Django 5.2.8 on 2026-01-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_slug'),
        ('usuarios', '0002_usuario_tiene_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('es_activo', models.BooleanField(default=True, verbose_name='¿Está activo en el equipo?')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenadores', to='equipos.equipo')),
                ('perfil_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='usuarios.perfilentrenador')),
            ],
            options={
                'verbose_name': 'Equipo - Entrenador',
                'verbose_name_plural': 'Equipos - Entrenadores',
                'ordering': ['equipo', 'perfil_entrenador'],
                'unique_together': {('equipo', 'perfil_entrenador')},
            },
        ),
        migrations.CreateModel(
            name='EquipoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('es_activo', models.BooleanField(default=True, verbose_name='¿Está activo en el equipo?')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipo')),
                ('perfil_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='usuarios.perfiljugador')),
            ],
            options={
                'verbose_name': 'Equipo - Jugador',
                'verbose_name_plural': 'Equipos - Jugadores',
                'ordering': ['equipo', 'perfil_jugador'],
                'unique_together': {('equipo', 'perfil_jugador')},
            },
        ),
    ]
