# Generated by Django 5.2.6 on 2026-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipojugador_fecha_salida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipojugador',
            options={'ordering': ['-fecha_incorporacion', 'equipo', 'perfil_jugador'], 'verbose_name': 'Equipo - Jugador', 'verbose_name_plural': 'Equipos - Jugadores'},
        ),
        migrations.AlterUniqueTogether(
            name='equipojugador',
            unique_together=set(),
        ),
    ]
