# Generated by Django 5.2.6 on 2026-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_alter_equipojugador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipoentrenador',
            options={'ordering': ['-fecha_incorporacion', 'equipo', 'perfil_entrenador'], 'verbose_name': 'Equipo - Entrenador', 'verbose_name_plural': 'Equipos - Entrenadores'},
        ),
        migrations.AlterUniqueTogether(
            name='equipoentrenador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipoentrenador',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
    ]
